---
### CONFIG - Infernus101 & Fris###
## On Streak message {streak} will be replaced by streak count of the killer!
on-streak-message: "You're on {streak} kill streak!"
## Streak lost message {streak} will be replaced by streak count of the dead player!
streak-lose-message: "Oh no! you lost your streak of {streak}!"
## Streak count : Streak command, the command will be executed once player reaches that streak!
## Tags:
## {player} will be replaced by player's name
## {streak} will be replaced by player's streak
5: 
  tell {player} {streak} kill streak!
  say {player} is on a {streak} killStreak!
10: 
  tell {player} {streak} kill streak!
  say {player} is on a {streak} killStreak!
...
